# SPDX-License-Identifier: GPL-3.0-only
#:schema https://jorge-menjivar.github.io/super-stt/registry.schema.json
# Super STT backend registry. One entry per installable backend, alphabetically
# sorted. See registry/README.md for the submission rules.

[deepgram]
    repo  = "github.com/jorge-menjivar/super-stt-deepgram"
    forge = "github"

[mistral]
    repo  = "github.com/jorge-menjivar/super-stt-mistral"
    forge = "github"

[openai]
    repo  = "github.com/jorge-menjivar/super-stt-openai"
    forge = "github"

[qwen3_asr]
    repo  = "github.com/jorge-menjivar/super-stt-qwen-asr"
    forge = "github"

[voxtral]
    repo  = "github.com/jorge-menjivar/super-stt-voxtral"
    forge = "github"

[whisper]
    repo  = "github.com/jorge-menjivar/super-stt-whisper"
    forge = "github"
