words = [
    "ack",
    "acks",
    "broadcasted",
    "cuda",
    "dbus",
    "fft",
    "keepalive",
    "kokoro",
    "menjivar",
    "openai",
    "piper",
    "safetensors",
    "serde",
    "tts",
    "typer",
    "udp",
    "vergen",
    "xtts",
]
