[package]
    name = "super-tts-install"
    version.workspace = true
    authors.workspace = true
    edition.workspace = true
    description = "Installer and self-updater for Super TTS"
    repository = "https://github.com/jorge-menjivar/super-tts"
    license = "GPL-3.0-only"

[dependencies]
    anyhow.workspace = true
    clap.workspace = true
    dirs.workspace = true
    env_logger.workspace = true
    flate2 = "1.1.9"
    log.workspace = true
    reqwest.workspace = true
    serde.workspace = true
    serde_json.workspace = true
    super-tts-forge = { path = "../super-tts-forge" }
    super-tts-registry-types = { path = "../super-tts-registry-types" }
    tar = "0.4.46"
    thiserror.workspace = true
    tokio.workspace = true

[dev-dependencies]
    hex = "0.4.3"
    mockito = "1"
    ring = "0.17.14"

[lints]
    workspace = true
