// SPDX-License-Identifier: GPL-3.0-only
pub mod about;
pub mod common;
pub mod connection;
pub mod customization;
pub mod input_simulation;
pub mod language_picker;
pub mod models;
pub mod recording;
pub mod updates;
